# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_degree', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_filename', models.CharField(max_length=1000)),
                ('short_filename', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Motion')),
                ('files', models.ManyToManyField(to='api.Files')),
            ],
        ),
        migrations.CreateModel(
            name='MotionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryGroup',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentarySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MotionType'),
        ),
        migrations.AddField(
            model_name='motion',
            name='parliamentary_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ParliamentaryGroup'),
        ),
        migrations.AddField(
            model_name='motion',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CouncilPerson'),
        ),
        migrations.AddField(
            model_name='motion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ParliamentarySession'),
        ),
        migrations.AddField(
            model_name='councilperson',
            name='parliamentary_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ParliamentaryGroup'),
        ),
    ]
