# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160727_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('files', models.ManyToManyField(to='api.File')),
                ('parliamentary_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ParliamentaryGroup')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CouncilPerson')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ParliamentarySession')),
            ],
        ),
        migrations.RemoveField(
            model_name='motion',
            name='motion_type',
        ),
        migrations.AlterField(
            model_name='motion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Answer'),
        ),
        migrations.DeleteModel(
            name='MotionType',
        ),
    ]
