# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_motion_motion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='motion_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
