# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160728_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='files',
            field=models.ManyToManyField(blank=True, to='api.File'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='answers',
            field=models.ManyToManyField(blank=True, to='api.Answer'),
        ),
    ]
