# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_answer_answered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentarygroup',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
